name = "forkit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

upload_source_maps = true

[assets]
not_found_handling = "single-page-application"

# Custom domain configuration
routes = [
  { pattern = "fork-it.cc", custom_domain = true },
  { pattern = "*.fork-it.cc", custom_domain = true }
]

# Environment variables should be set in the Cloudflare dashboard
# DO NOT put sensitive keys in this file 