name = "forkit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[site]
bucket = "./dist"
entry-point = "workers-site"

# Custom domain configuration
[[routes]]
pattern = "fork-it.cc"
custom_domain = true

# Environment variables should be set in the Cloudflare dashboard
# DO NOT put sensitive keys in this file 