name = "forkit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"

# Custom domain configuration
[[routes]]
pattern = "fork-it.cc"
custom_domain = true

# SPA routing configuration
[[routes]]
pattern = "/*"
script = "index.html"

# Environment variables should be set in the Cloudflare dashboard
# DO NOT put sensitive keys in this file 