name = "forkit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

upload_source_maps = true

[assets]
not_found_handling = "single-page-application" 