name = "forkit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
main = "workers/session-api.js"

# Specify that we're using ES modules
[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./workers/session-api.js"
dir = "."

[observability]
enabled = true

# Custom domain configuration
[[routes]]
pattern = "fork-it.cc"
custom_domain = true

[[routes]]
pattern = "fork-it.cc/api/*"
custom_domain = true

# KV namespace for storing sessions
[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "054a532157ab4303bcba93e6ee2495d2"
preview_id = "ea025c77f4ff4fa0bc5b7c3ff57f68d6"

# Environment variables should be set in the Cloudflare dashboard
# DO NOT put sensitive keys in this file 