name = "forkit"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[site]
bucket = "./dist"
entry-point = "workers-site"

# Custom domain configuration
[[routes]]
pattern = "fork-it.cc"
custom_domain = true

# KV namespace for storing sessions
[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "your-kv-namespace-id" # Replace with your actual KV namespace ID
preview_id = "your-preview-kv-namespace-id" # Replace with your actual preview KV namespace ID

# Environment variables should be set in the Cloudflare dashboard
# DO NOT put sensitive keys in this file 